language: android
android:
  components:
  - tools
  - platform-tools
  - build-tools-26.0.2
  - android-26
  licenses:
  - android-sdk-license-.+
addons:
  sonarcloud:
    organization: sonarqubesoen390briar-github
    token:
      secure: ${SONAR_TOKEN}
    branches:
      - master
      - dev
before_install:
- yes | sdkmanager "platforms;android-27"
- ./gradlew clean test
script:
- cd /home/travis/build/jhubscher/briarproject_390/build/intermediates/classes
- ls
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'
