language: android
android:
  components:
  - tools
  - platform-tools
  - build-tools-26.0.2
  - android-26
  licenses:
  - android-sdk-license-.+
addons:
  sonarcloud:
    organization: sonarqubesoen390briar-github
    token:
      secure: ${SONAR_TOKEN}
    branches:
      - dev
before_install:
  - yes | sdkmanager "platforms;android-27" 
stages:
  - compile
  - test
  - static_analysis
jobs:
    include: 
      - stage: compile
        script: 
          ./gradlew clean assemble
      - stage: test
        script: 
          ./gradlew test --rerun-tasks --continue
      - stage: sonar
        script: 
          sonar-scanner
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'