language: android
android:
  components:
  - tools
  - platform-tools
  - build-tools-26.0.2
  - android-26
  licenses:
  - android-sdk-license-.+
addons:
  sonarcloud:
    organization: sonarqubesoen390briar-github
    token:
      secure: ${SONAR_TOKEN}
    branches:
      - master
      - dev
before_install:
  - yes | sdkmanager "platforms;android-27"
stages:
  - compile
  - sonar
  - test

jobs:
    include:
      - stage: compile
        script:
          ./gradlew clean assemble
      - stage: sonar
        script:
             - if [ ($TRAVIS_BRANCH == "dev") || ($TRAVIS_BRANCH == "master")  ]; then ./gradlew clean assemble && sonar-scanner; fi
      - stage: test
        script:
          ./gradlew test --info --rerun-tasks --continue
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'
