language: android
android:
  components:
  - tools
  - platform-tools
  - build-tools-26.0.2
  - android-26
  licenses:
  - android-sdk-license-.+
addons:
  sonarcloud:
    organization: "sonarqubesoen390briar-github"
    token:
      secure: "186bfbb22bba3fdf57590a6c601f427fba76946d"
    branches:
      - dev
before_install:
  - yes | sdkmanager "platforms;android-27"
stages:
  - compile
  - sonar
  - test

jobs:
    include:
      - stage: compile
        script:
          ./gradlew clean assemble
      - stage: sonar
        script:
          sonar-scanner
      - stage: test
        script:
          ./gradlew test --info --rerun-tasks --continue
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'
